deployment:
  tasks:
    - export NODE_VERSION=23
    - export DEPLYPATH=/home/loanc306/public_html
    - /opt/cpanel/ea-nodejs23/bin/npm install
    - /opt/cpanel/ea-nodejs23/bin/npm run build
    - /bin/rsync -av --delete build/ $DEPLOYPATH
